[2023-03-17 21:00:01,553] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: reto_tecnico_everst.download_data scheduled__2023-03-17T20:00:00+00:00 [queued]>
[2023-03-17 21:00:01,562] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: reto_tecnico_everst.download_data scheduled__2023-03-17T20:00:00+00:00 [queued]>
[2023-03-17 21:00:01,563] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-03-17 21:00:01,563] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-03-17 21:00:01,564] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-03-17 21:00:01,617] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): download_data> on 2023-03-17 20:00:00+00:00
[2023-03-17 21:00:01,642] {standard_task_runner.py:52} INFO - Started process 4541 to run task
[2023-03-17 21:00:01,664] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'reto_tecnico_everst', 'download_data', 'scheduled__2023-03-17T20:00:00+00:00', '--job-id', '242', '--raw', '--subdir', 'DAGS_FOLDER/reto_tecnico_everst.py', '--cfg-path', '/tmp/tmpo65azgww', '--error-file', '/tmp/tmphohrrk4h']
[2023-03-17 21:00:01,665] {standard_task_runner.py:80} INFO - Job 242: Subtask download_data
[2023-03-17 21:00:01,878] {task_command.py:369} INFO - Running <TaskInstance: reto_tecnico_everst.download_data scheduled__2023-03-17T20:00:00+00:00 [running]> on host 7d9c3e4a2f58
[2023-03-17 21:00:02,095] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=reto_tecnico_everst
AIRFLOW_CTX_TASK_ID=download_data
AIRFLOW_CTX_EXECUTION_DATE=2023-03-17T20:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-17T20:00:00+00:00
[2023-03-17 21:00:07,149] {reto_tecnico_everst.py:41} INFO - Generando descarga del GZ
[2023-03-17 21:00:11,207] {reto_tecnico_everst.py:48} INFO - Guardando la base generada desde el API, path: dags/data/Raw/base_api/base_20230317_21.00.json
[2023-03-17 21:00:22,457] {python.py:173} INFO - Done. Returned value was: None
[2023-03-17 21:00:22,479] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=reto_tecnico_everst, task_id=download_data, execution_date=20230317T200000, start_date=20230317T210001, end_date=20230317T210022
[2023-03-17 21:00:22,626] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-03-17 21:00:22,707] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2023-03-17 21:04:59,008] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: reto_tecnico_everst.download_data scheduled__2023-03-17T20:00:00+00:00 [queued]>
[2023-03-17 21:04:59,017] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: reto_tecnico_everst.download_data scheduled__2023-03-17T20:00:00+00:00 [queued]>
[2023-03-17 21:04:59,018] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-03-17 21:04:59,019] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-03-17 21:04:59,019] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-03-17 21:04:59,070] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): download_data> on 2023-03-17 20:00:00+00:00
[2023-03-17 21:04:59,076] {standard_task_runner.py:52} INFO - Started process 4667 to run task
[2023-03-17 21:04:59,079] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'reto_tecnico_everst', 'download_data', 'scheduled__2023-03-17T20:00:00+00:00', '--job-id', '249', '--raw', '--subdir', 'DAGS_FOLDER/reto_tecnico_everst.py', '--cfg-path', '/tmp/tmp3psqjmet', '--error-file', '/tmp/tmpvdjgcxfs']
[2023-03-17 21:04:59,080] {standard_task_runner.py:80} INFO - Job 249: Subtask download_data
[2023-03-17 21:04:59,382] {task_command.py:369} INFO - Running <TaskInstance: reto_tecnico_everst.download_data scheduled__2023-03-17T20:00:00+00:00 [running]> on host 7d9c3e4a2f58
[2023-03-17 21:04:59,652] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=reto_tecnico_everst
AIRFLOW_CTX_TASK_ID=download_data
AIRFLOW_CTX_EXECUTION_DATE=2023-03-17T20:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-17T20:00:00+00:00
[2023-03-17 21:05:04,174] {reto_tecnico_everst.py:41} INFO - Generando descarga del GZ
[2023-03-17 21:05:08,886] {reto_tecnico_everst.py:48} INFO - Guardando la base generada desde el API, path: dags/data/Raw/base_api/base_20230317_21.05.json
[2023-03-17 21:05:21,422] {python.py:173} INFO - Done. Returned value was: None
[2023-03-17 21:05:21,437] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=reto_tecnico_everst, task_id=download_data, execution_date=20230317T200000, start_date=20230317T210459, end_date=20230317T210521
[2023-03-17 21:05:21,581] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-03-17 21:05:21,676] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2023-03-17 21:55:47,339] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: reto_tecnico_everst.download_data scheduled__2023-03-17T20:00:00+00:00 [queued]>
[2023-03-17 21:55:47,350] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: reto_tecnico_everst.download_data scheduled__2023-03-17T20:00:00+00:00 [queued]>
[2023-03-17 21:55:47,351] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-03-17 21:55:47,352] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-03-17 21:55:47,352] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-03-17 21:55:47,409] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): download_data> on 2023-03-17 20:00:00+00:00
[2023-03-17 21:55:47,419] {standard_task_runner.py:52} INFO - Started process 236 to run task
[2023-03-17 21:55:47,426] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'reto_tecnico_everst', 'download_data', 'scheduled__2023-03-17T20:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/reto_tecnico_everst.py', '--cfg-path', '/tmp/tmprsgb2536', '--error-file', '/tmp/tmppxaitkdo']
[2023-03-17 21:55:47,429] {standard_task_runner.py:80} INFO - Job 3: Subtask download_data
[2023-03-17 21:55:47,743] {task_command.py:369} INFO - Running <TaskInstance: reto_tecnico_everst.download_data scheduled__2023-03-17T20:00:00+00:00 [running]> on host 8b817a59af06
[2023-03-17 21:55:48,303] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=reto_tecnico_everst
AIRFLOW_CTX_TASK_ID=download_data
AIRFLOW_CTX_EXECUTION_DATE=2023-03-17T20:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-17T20:00:00+00:00
[2023-03-17 21:55:50,178] {reto_tecnico_everst.py:37} ERROR - Se genero un Error al intentar conectar con la url: https://smn.conagua.gob.mx/webservices/index.php?method=3
[2023-03-17 21:55:50,179] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/airflow/dags/reto_tecnico_everst.py", line 35, in download_data
    gz_content = urlopen(request_site).read()
  File "/usr/local/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/local/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/lib/python3.7/urllib/request.py", line 563, in error
    result = self._call_chain(*args)
  File "/usr/local/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.7/urllib/request.py", line 755, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/local/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/local/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/local/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/reto_tecnico_everst.py", line 38, in download_data
    raise AirflowFailException(e)
airflow.exceptions.AirflowFailException: HTTP Error 404: Not Found
[2023-03-17 21:55:50,194] {taskinstance.py:1400} INFO - Immediate failure requested. Marking task as FAILED. dag_id=reto_tecnico_everst, task_id=download_data, execution_date=20230317T200000, start_date=20230317T215547, end_date=20230317T215550
[2023-03-17 21:55:50,221] {standard_task_runner.py:97} ERROR - Failed to execute job 3 for task download_data (HTTP Error 404: Not Found; 236)
[2023-03-17 21:55:50,265] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-03-17 21:55:50,367] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
