[2023-03-17 21:02:13,258] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: reto_tecnico_everst.create_current_base3_copy manual__2023-03-17T20:51:12.795663+00:00 [queued]>
[2023-03-17 21:02:13,269] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: reto_tecnico_everst.create_current_base3_copy manual__2023-03-17T20:51:12.795663+00:00 [queued]>
[2023-03-17 21:02:13,270] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-03-17 21:02:13,271] {taskinstance.py:1357} INFO - Starting attempt 2 of 2
[2023-03-17 21:02:13,271] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-03-17 21:02:13,319] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): create_current_base3_copy> on 2023-03-17 20:51:12.795663+00:00
[2023-03-17 21:02:13,327] {standard_task_runner.py:52} INFO - Started process 4615 to run task
[2023-03-17 21:02:13,331] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'reto_tecnico_everst', 'create_current_base3_copy', 'manual__2023-03-17T20:51:12.795663+00:00', '--job-id', '247', '--raw', '--subdir', 'DAGS_FOLDER/reto_tecnico_everst.py', '--cfg-path', '/tmp/tmp2e6jmp2l', '--error-file', '/tmp/tmpnyhi6_i0']
[2023-03-17 21:02:13,333] {standard_task_runner.py:80} INFO - Job 247: Subtask create_current_base3_copy
[2023-03-17 21:02:13,490] {task_command.py:369} INFO - Running <TaskInstance: reto_tecnico_everst.create_current_base3_copy manual__2023-03-17T20:51:12.795663+00:00 [running]> on host 7d9c3e4a2f58
[2023-03-17 21:02:13,638] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=reto_tecnico_everst
AIRFLOW_CTX_TASK_ID=create_current_base3_copy
AIRFLOW_CTX_EXECUTION_DATE=2023-03-17T20:51:12.795663+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-17T20:51:12.795663+00:00
[2023-03-17 21:02:13,641] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2023-03-17 21:02:13,642] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'cp /opt/***/None /opt/***/dags/data/Analytics/base_3/base_3_current.parquet']
[2023-03-17 21:02:13,658] {subprocess.py:85} INFO - Output:
[2023-03-17 21:02:13,668] {subprocess.py:92} INFO - cp: cannot stat '/opt/***/None': No such file or directory
[2023-03-17 21:02:13,668] {subprocess.py:96} INFO - Command exited with return code 1
[2023-03-17 21:02:13,757] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-03-17 21:02:13,768] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=reto_tecnico_everst, task_id=create_current_base3_copy, execution_date=20230317T205112, start_date=20230317T210213, end_date=20230317T210213
[2023-03-17 21:02:13,836] {standard_task_runner.py:97} ERROR - Failed to execute job 247 for task create_current_base3_copy (Bash command failed. The command returned a non-zero exit code 1.; 4615)
[2023-03-17 21:02:13,865] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-03-17 21:02:13,927] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
