[2023-03-17 20:54:26,642] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: reto_tecnico_everst.table_by_municipio manual__2023-03-17T20:51:12.795663+00:00 [queued]>
[2023-03-17 20:54:26,653] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: reto_tecnico_everst.table_by_municipio manual__2023-03-17T20:51:12.795663+00:00 [queued]>
[2023-03-17 20:54:26,654] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-03-17 20:54:26,655] {taskinstance.py:1357} INFO - Starting attempt 2 of 2
[2023-03-17 20:54:26,656] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-03-17 20:54:26,806] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): table_by_municipio> on 2023-03-17 20:51:12.795663+00:00
[2023-03-17 20:54:26,815] {standard_task_runner.py:52} INFO - Started process 4452 to run task
[2023-03-17 20:54:26,823] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'reto_tecnico_everst', 'table_by_municipio', 'manual__2023-03-17T20:51:12.795663+00:00', '--job-id', '238', '--raw', '--subdir', 'DAGS_FOLDER/reto_tecnico_everst.py', '--cfg-path', '/tmp/tmpkb26_8es', '--error-file', '/tmp/tmp47xqr5j1']
[2023-03-17 20:54:26,824] {standard_task_runner.py:80} INFO - Job 238: Subtask table_by_municipio
[2023-03-17 20:54:26,988] {task_command.py:369} INFO - Running <TaskInstance: reto_tecnico_everst.table_by_municipio manual__2023-03-17T20:51:12.795663+00:00 [running]> on host 7d9c3e4a2f58
[2023-03-17 20:54:27,127] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=reto_tecnico_everst
AIRFLOW_CTX_TASK_ID=table_by_municipio
AIRFLOW_CTX_EXECUTION_DATE=2023-03-17T20:51:12.795663+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-17T20:51:12.795663+00:00
[2023-03-17 20:54:27,145] {reto_tecnico_everst.py:57} INFO - Leyendo la base extraida del API
[2023-03-17 20:54:32,428] {reto_tecnico_everst.py:70} INFO - Formateando los tipos de datos en el DataFrame.
[2023-03-17 20:54:32,467] {logging_mixin.py:115} WARNING - /opt/***/dags/reto_tecnico_everst.py:71 SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2023-03-17 20:54:32,476] {logging_mixin.py:115} WARNING - /opt/***/dags/reto_tecnico_everst.py:72 SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2023-03-17 20:54:32,484] {logging_mixin.py:115} WARNING - /opt/***/dags/reto_tecnico_everst.py:73 SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2023-03-17 20:54:32,492] {logging_mixin.py:115} WARNING - /opt/***/dags/reto_tecnico_everst.py:74 SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2023-03-17 20:54:32,493] {reto_tecnico_everst.py:75} INFO - Creando el promedio de temperatura y precipitación de las últimas dos horas.
[2023-03-17 20:54:32,496] {logging_mixin.py:115} WARNING - /opt/***/dags/reto_tecnico_everst.py:76 FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
[2023-03-17 20:54:32,567] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 3361, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 76, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'column name'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/reto_tecnico_everst.py", line 77, in table_by_municipio
    n_df['column name'] = df['column name'].astype(np.int64)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/frame.py", line 3458, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 3363, in get_loc
    raise KeyError(key) from err
KeyError: 'column name'
[2023-03-17 20:54:32,615] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=reto_tecnico_everst, task_id=table_by_municipio, execution_date=20230317T205112, start_date=20230317T205426, end_date=20230317T205432
[2023-03-17 20:54:32,659] {standard_task_runner.py:97} ERROR - Failed to execute job 238 for task table_by_municipio ('column name'; 4452)
[2023-03-17 20:54:32,716] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-03-17 20:54:32,855] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
